spring:
  application:
    name: microservice-simple-consumer-movie
server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true